name: phone_ide
description: PhoneIDE freeCodeCamps Mobile Editor Made with Flutter.
version: 1.0.2+1
repository: https://github.com/freeCodeCamp/PhoneIDE
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  property_change_notifier: ^0.3.0
  shared_preferences: ^2.0.13
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf